### ISSUE TITLE
git-swear-stats works, but git swear-stats doesn't

### ISSUE THREAD

**Issue by revdan** [xiongchiamiov/git-swear-stats#3]
The latter gives this:

```
/Users/me/.rvm/gems/ruby-1.9.3-p392/gems/git-swear-stats-0.1.0/bin/git-swear-stats:103: undefined method `force_encoding' for #<String:0x105f00f40> (NoMethodError)
from     /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `each_with_index'
from /Users/me/.rvm/gems/ruby-1.9.3-p392/gems/git-1.2.5/lib/git/log.rb:85:in `each'
from /Users/me/.rvm/gems/ruby-1.9.3-p392/gems/git-1.2.5/lib/git/log.rb:85:in `each'
from /Users/me/.rvm/gems/ruby-1.9.3-p392/gems/git-swear-stats-0.1.0/bin/git-swear-stats:64:in `each_with_index'
from /Users/me/.rvm/gems/ruby-1.9.3-p392/gems/git-swear-stats-0.1.0/bin/git-swear-stats:64
from /usr/bin/git-swear-stats:19:in `load'
from /usr/bin/git-swear-stats:19
Parsing git log%
```

**Comment by xiongchiamiov** [comment]
You've got something really funky going on with your rvm installation - the first line of the stack trace shows the code running in 1.9.3, but the second line is using code from 1.8!

It should work if I fix #1, but that seems like it's going to just cause you all sorts of problems down the road.

**Comment by revdan** [comment]
Shit man, you're right. Time to set fire to my machine. You can probably close this.

**Comment by revdan** [comment]
:poop:
